# Generated by Django 5.2.6 on 2025-09-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('consumable', 'Konsumsi'), ('equipment', 'Perlengkapan'), ('tool', 'Alat'), ('treasure', 'Barang Berharga'), ('misc', 'Lain-Lain')], default='misc', max_length=255),
        ),
    ]
